#elasticsearch.clustername=Cluster1
#elasticsearch.host=localhost
#elasticsearch.port=9200

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
#  datasource:
#    url: jdbc:mysql://localhost:3306/study_db?serverTimezone=UTC&characterEncoding=UTF-8
#    username: tester
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true


  jpa:
#    database: mysql
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace